package projeto;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author 20171174010006
 */
public class pnivel2 extends javax.swing.JFrame {
    ArrayList<Questao> arrayQuestoes = new ArrayList<>();
    private String user;
    public void user(String u) {
        user = u;
    }
    /**
     * Creates new form pnivel2
     */
    public pnivel2() {
        initComponents();
        Questoes3 q3 = new Questoes3();
        int numeroSorteado = q3.randomizar();
        Questao q = q3.questao.get(numeroSorteado);
        enunciado2.setText(arrayQuestoes.get(0).enunciado);
        usertext.setText(user);
        System.out.println(user);
        enunciado.add("Questao 1");
        enunciado.add("Questao 2");
        enunciado.add("Questao 3");
        enunciado.add("Questao 4");
        enunciado.add("Questao 5");
        enunciado.add("Questao 6");
        enunciado.add("Questao 7");
        enunciado.add("Questao 8");
        enunciado.add("Questao 9");
        enunciado.add("Questao 10");
        enunciado.add("Questao 11");
        enunciado.add("Questao 12");
        enunciado.add("Questao 13");
        enunciado.add("Questao 14");
        enunciado.add("Questao 15");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        rD2 = new javax.swing.JRadioButton();
        rC2 = new javax.swing.JRadioButton();
        rB2 = new javax.swing.JRadioButton();
        rE2 = new javax.swing.JRadioButton();
        rA2 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        enunciado2 = new javax.swing.JLabel();
        NQ2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        usertext = new javax.swing.JLabel();
        numeroQ2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 51, 153));
        jPanel1.setPreferredSize(new java.awt.Dimension(832, 545));

        jLabel1.setFont(new java.awt.Font("Sylfaen", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Questão:");

        rD2.setBackground(new java.awt.Color(0, 51, 153));
        rD2.setForeground(new java.awt.Color(255, 255, 255));
        rD2.setText("D");
        rD2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rD2ActionPerformed(evt);
            }
        });

        rC2.setBackground(new java.awt.Color(0, 51, 153));
        rC2.setForeground(new java.awt.Color(255, 255, 255));
        rC2.setText("C");
        rC2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rC2ActionPerformed(evt);
            }
        });

        rB2.setBackground(new java.awt.Color(0, 51, 153));
        rB2.setForeground(new java.awt.Color(255, 255, 255));
        rB2.setText("B");
        rB2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rB2ActionPerformed(evt);
            }
        });

        rE2.setBackground(new java.awt.Color(0, 51, 153));
        rE2.setForeground(new java.awt.Color(255, 255, 255));
        rE2.setText("E");

        rA2.setBackground(new java.awt.Color(0, 51, 153));
        rA2.setForeground(new java.awt.Color(255, 255, 255));
        rA2.setText("A");
        rA2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rA2ActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(51, 153, 0));
        jButton1.setText("Confirma");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        enunciado2.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        enunciado2.setForeground(new java.awt.Color(255, 255, 255));
        enunciado2.setText("ENUNCIADO2");

        NQ2.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        NQ2.setForeground(new java.awt.Color(255, 255, 255));
        NQ2.setText("Qustões respondidas:");

        jButton2.setBackground(new java.awt.Color(255, 0, 0));
        jButton2.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Desistir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        numeroQ2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        numeroQ2.setForeground(new java.awt.Color(204, 0, 0));
        numeroQ2.setText("0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(enunciado2, javax.swing.GroupLayout.PREFERRED_SIZE, 647, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(159, 159, 159))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(rA2)
                                .addGap(55, 55, 55)
                                .addComponent(rB2)
                                .addGap(57, 57, 57)
                                .addComponent(rC2)
                                .addGap(60, 60, 60)
                                .addComponent(rD2)
                                .addGap(59, 59, 59)
                                .addComponent(rE2)
                                .addGap(63, 63, 63)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 152, Short.MAX_VALUE))
                            .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addContainerGap())))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(NQ2, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(numeroQ2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(usertext, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(enunciado2, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rA2)
                    .addComponent(rB2)
                    .addComponent(rC2)
                    .addComponent(rD2)
                    .addComponent(rE2)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 160, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(usertext, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(NQ2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(numeroQ2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 509, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rC2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rC2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rC2ActionPerformed

    private void rD2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rD2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rD2ActionPerformed

    private void rB2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rB2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rB2ActionPerformed

    private void rA2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rA2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rA2ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       new Quiz().setVisible(true);      
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed
int x = 0;
    ArrayList<String> enunciado = new ArrayList<>();

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (x < arrayQuestoes.size()) {
            enunciado2.setText(enunciado.get(x));
            System.out.println(arrayQuestoes.get(x).getEnunciado());
            numeroQ2.setText(String.valueOf(++x));
        }else{
                        JOptionPane.showMessageDialog(null, "Limite de questoes atingidas");
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pnivel2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pnivel2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pnivel2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pnivel2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pnivel2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel NQ2;
    private javax.swing.JLabel enunciado2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel numeroQ2;
    private javax.swing.JRadioButton rA2;
    private javax.swing.JRadioButton rB2;
    private javax.swing.JRadioButton rC2;
    private javax.swing.JRadioButton rD2;
    private javax.swing.JRadioButton rE2;
    private javax.swing.JLabel usertext;
    // End of variables declaration//GEN-END:variables
}
