/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projeto;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Weslley Leocadio
 */
public class pnivel1 extends javax.swing.JFrame {

    ArrayList<Questao> arrayQuestoes = new ArrayList<>();
    private String user;

    public void user(String u) {
        user = u;
    }

    public pnivel1() {
        initComponents();

        questoes1 q1 = new questoes1();
        arrayQuestoes = q1.Questao1();
        enunciado1.setText(arrayQuestoes.get(0).enunciado);
        usertext.setText(user);
        System.out.println(user);
        enunciado.add("Questao 1");
        enunciado.add("Questao 2");
        enunciado.add("Questao 3");
        enunciado.add("Questao 4");
        enunciado.add("Questao 5");
        enunciado.add("Questao 6");
        enunciado.add("Questao 7");
        enunciado.add("Questao 8");
        enunciado.add("Questao 9");
        enunciado.add("Questao 10");
        enunciado.add("Questao 11");
        enunciado.add("Questao 12");
        enunciado.add("Questao 13");
        enunciado.add("Questao 14");
        enunciado.add("Questao 15");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        rA1 = new javax.swing.JRadioButton();
        rB1 = new javax.swing.JRadioButton();
        rC1 = new javax.swing.JRadioButton();
        rD1 = new javax.swing.JRadioButton();
        rE1 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        enunciado1 = new javax.swing.JLabel();
        NQ1 = new javax.swing.JLabel();
        Desistir1 = new javax.swing.JButton();
        numeroQ1 = new javax.swing.JLabel();
        usertext = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 51, 153));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Sylfaen", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Questão;");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        rA1.setBackground(new java.awt.Color(0, 0, 153));
        rA1.setForeground(new java.awt.Color(255, 255, 255));
        rA1.setText("A");

        rB1.setBackground(new java.awt.Color(0, 0, 153));
        rB1.setForeground(new java.awt.Color(255, 255, 255));
        rB1.setText("B");

        rC1.setBackground(new java.awt.Color(0, 0, 153));
        rC1.setForeground(new java.awt.Color(255, 255, 255));
        rC1.setText("C");
        rC1.setMaximumSize(new java.awt.Dimension(30, 23));
        rC1.setMinimumSize(new java.awt.Dimension(30, 23));

        rD1.setBackground(new java.awt.Color(0, 0, 153));
        rD1.setForeground(new java.awt.Color(255, 255, 255));
        rD1.setText("D");
        rD1.setMaximumSize(new java.awt.Dimension(30, 23));
        rD1.setMinimumSize(new java.awt.Dimension(30, 23));

        rE1.setBackground(new java.awt.Color(0, 0, 153));
        rE1.setForeground(new java.awt.Color(255, 255, 255));
        rE1.setText("E");
        rE1.setMaximumSize(new java.awt.Dimension(30, 23));
        rE1.setMinimumSize(new java.awt.Dimension(30, 23));

        jButton1.setBackground(new java.awt.Color(0, 153, 51));
        jButton1.setText("Confirma");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        enunciado1.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        enunciado1.setForeground(new java.awt.Color(255, 255, 255));
        enunciado1.setText("ENUNCIADO1");

        NQ1.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        NQ1.setForeground(new java.awt.Color(255, 255, 255));
        NQ1.setText("Questões respondidas:");

        Desistir1.setBackground(new java.awt.Color(255, 0, 0));
        Desistir1.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        Desistir1.setForeground(new java.awt.Color(255, 255, 255));
        Desistir1.setText("Desistir");
        Desistir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Desistir1ActionPerformed(evt);
            }
        });

        numeroQ1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        numeroQ1.setForeground(new java.awt.Color(204, 0, 0));
        numeroQ1.setText("0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(118, 118, 118)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(enunciado1, javax.swing.GroupLayout.PREFERRED_SIZE, 615, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(rA1)
                                        .addGap(56, 56, 56)
                                        .addComponent(rB1)
                                        .addGap(58, 58, 58)
                                        .addComponent(rC1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(55, 55, 55)
                                        .addComponent(rD1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(49, 49, 49)
                                        .addComponent(rE1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(43, 43, 43)
                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(NQ1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(numeroQ1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 111, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(268, 268, 268)
                                .addComponent(Desistir1))
                            .addComponent(usertext, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Desistir1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(enunciado1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rB1)
                    .addComponent(rA1)
                    .addComponent(rC1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rD1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rE1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 141, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NQ1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(numeroQ1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(usertext, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Desistir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Desistir1ActionPerformed
        new Quiz().setVisible(true);
        dispose();
    }//GEN-LAST:event_Desistir1ActionPerformed
    int x = 0;
    ArrayList<String> enunciado = new ArrayList<>();
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (x < arrayQuestoes.size()) {
            enunciado1.setText(enunciado.get(x));
            System.out.println(arrayQuestoes.get(x).getEnunciado());
            numeroQ1.setText(String.valueOf(++x));
        } else {
            JOptionPane.showMessageDialog(null, "Limite de questoes atingidas");
    }//GEN-LAST:event_jButton1ActionPerformed
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pnivel1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pnivel1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pnivel1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pnivel1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pnivel1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Desistir1;
    private javax.swing.JLabel NQ1;
    private javax.swing.JLabel enunciado1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel numeroQ1;
    private javax.swing.JRadioButton rA1;
    private javax.swing.JRadioButton rB1;
    private javax.swing.JRadioButton rC1;
    private javax.swing.JRadioButton rD1;
    private javax.swing.JRadioButton rE1;
    private javax.swing.JLabel usertext;
    // End of variables declaration//GEN-END:variables
}
